---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: mosquitto
      version: 4.8.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    persistence:
      config:
        enabled: true
        existingClaim: mosquitto-config-v1
      data:
        enabled: true
        existingClaim: mosquitto-data-v1

    resources:
      # requests:
      #   cpu: 15m
      #   memory: 64Mi
      # limits:
      #   cpu: 38m
      #   memory: 64Mi
