# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: '${EXTERNAL_DOMAIN/./-}'
#   namespace: network-system
# spec:
#   # secretTemplate:
#   #   annotations:
#   #     reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
#   #     reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kasten-io"
#   secretName: '${EXTERNAL_DOMAIN/./-}-tls'
#   issuerRef:
#     name: letsencrypt-production
#     kind: ClusterIssuer
#   commonName: '${EXTERNAL_DOMAIN}'
#   dnsNames:
#     - '${EXTERNAL_DOMAIN}'
#     - '*.${EXTERNAL_DOMAIN}'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '${INTERNAL_DOMAIN/./-}'
  namespace: network-system
spec:
  # secretTemplate:
  #   annotations:
  #     reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  #     reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kasten-io"
  secretName: '${INTERNAL_DOMAIN/./-}-tls'
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: '${INTERNAL_DOMAIN}'
  dnsNames:
    - '${INTERNAL_DOMAIN}'
    - '*.${INTERNAL_DOMAIN}'
