# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
stringData:
    api-token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1du4ayen4huhh45xd2u26mp72jay2mlw9n6vhk7vkuhfqyy8x5adqfwm8kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqK0NaTlB3YnBzL1RZQ3hS
            ZTZBeW0zZ2ppcHppWjFtZkdxOHUvOGk2eUdRCmFBMjh4QnhQM1VpZUU1WVRnWlZn
            WlJEYXVwMGFuSUNQTW9Sb2t5SG1PQ0EKLS0tIFJOMlRRY0luV1c1aFAxWmdOaGJl
            RjYrelorN0xiN2RIbDVGbWt2d1llM2MKz1tFn370O7WGaRcDo3kNOT/OgUuPVFF1
            w04d9tB+tIwFkxf2mMTyRa//A/7Cn3WOVWwRLpSrFbUtsF22eI2jig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T14:26:52Z"
    mac: ENC[AES256_GCM,data:XsS0DdaSXnIrao6YbnhS4z8kDnoBpPL0tF+F+96+ncMADog+kjNr3DN7OxQP0G2Xl1JoiXSYZ3yDDpTkrcYMOvnb/dzjhekYyKQvW/dbPTHVPJ9f3O5dZhamZLuBv/FVN1IQdbgn9ymvvNcvYLi/M4ksY/1yCqcEgEECybBEedU=,iv:ND1jnt3Jbt6bzLPhArR0f++O+q1PBteO2sC84gOPa5k=,tag:ql58vAk8FFnwBK7hkissAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
