---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: '^(kind)$'
    age: >-
      age1du4ayen4huhh45xd2u26mp72jay2mlw9n6vhk7vkuhfqyy8x5adqfwm8kn
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: '^(data|stringData)$'
    age: >-
      age1du4ayen4huhh45xd2u26mp72jay2mlw9n6vhk7vkuhfqyy8x5adqfwm8kn
  - path_regex: k8s/.*\.ya?ml
    encrypted_regex: '^(data|stringData)$'
    age: >-
      age1du4ayen4huhh45xd2u26mp72jay2mlw9n6vhk7vkuhfqyy8x5adqfwm8kn
