# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack
    namespace: system-monitoring
stringData:
    discord-webhook: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1du4ayen4huhh45xd2u26mp72jay2mlw9n6vhk7vkuhfqyy8x5adqfwm8kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5clZYd0NHdTN2anBjTTB1
            RTVQTVowMnhydURUOGZTeTdEYnl5K1pwUkVvCnNhK1A0SGt3UE1RTlJPUHFpWlhF
            cE9qb09YTUdPRlJ3WWRYTUNZUnRyOE0KLS0tIDNUMjdpYzZrcllTWE0raC80VmFp
            cFFEKzVlK3RJdm1tM3dSa3pTT3liRHMK1btsR6HngLbcwnuAcmFYc1KKY3Fg8vk/
            SucZH5PN/r2D3OjZcEG51IGxY8+RPHjeCwl2llI9IsXYVqyaKjtkZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T14:46:33Z"
    mac: ENC[AES256_GCM,data:gK6gedV7C9OymgEW1ouvfHEDJUeOaod1i9ZWn8wO8i4F0mViTEpYuTpCZ92WeLtmbxh2ONDIGhwnIrCMiPQhwTPiGSD7OnWekU8iXmcXC1/qOtowKXysoL0FcmWCGI3Nblr2X8JgBlLFfH7C7XqxFnXPnPrgUJzYWInxo1sAlT8=,iv:hg7UyTader33HqjaTAOQiqFkXYCptNser+N87h1e4Dk=,tag:WFCNmWnW1S8IjyVyUvcdtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
