---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docker-registry
  namespace: default
spec:
  interval: 1h
  chart:
    spec:
      chart: ./charts/docker-registry
      version: 1.9.9
      sourceRef:
        kind: GitRepository
        name: codehoschi-charts
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: registry
      tag: 2.8.1
    persistence:
      enabled: true
      size: 10Gi
      storageClass: nfs-client
    ingress:
      enabled: true
      className: 'traefik'
      annotations:
        # cert-manager.io/cluster-issuer: "letsencrypt-production"
        cert-manager.io/cluster-issuer: 'selfsigned-cluster-issuer'
        hajimari.io/enable: 'true'
        hajimari.io/icon: 'docker'
        traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
      hosts:
        # - host: 'registry.${SECRET_DOMAIN}'
        - 'registry.kube.lmwpva.de'
      path: '/'
      tls:
        - hosts:
            # - 'registry.${SECRET_DOMAIN}'
            - 'registry.kube.lmwpva.de'
          secretName: docker-regitry-tls
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 96Mi
