---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: k8s-at-home/paperless
      version: 8.8.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    #image:
    # repository: registry
    #tag: v0.1.4
    # persistence:
    #   enabled: true
    #   size: 10Gi
    #   storageClass: nfs-client
    persistence:
      data:
        enabled: true
        existingClaim: paperless-data
      media:
        enabled: true
        existingClaim: paperless-media
      consume:
        enabled: true
        existingClaim: paperless-consume
      export:
        enabled: true
        existingClaim: paperless-export
    env:
      PAPERLESS_OCR_LANGUAGE: ger
    ingress:
      enabled: true
      className: 'traefik'
      annotations:
        # cert-manager.io/cluster-issuer: "letsencrypt-production"
        cert-manager.io/cluster-issuer: 'selfsigned-cluster-issuer'
        hajimari.io/enable: 'true'
        hajimari.io/icon: 'api'
        traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
      hosts:
        # - host: 'registry.${SECRET_DOMAIN}'
        - 'paper.kube.lmwpva.de'
      path: '/'
      tls:
        - hosts:
            # - 'registry.${SECRET_DOMAIN}'
            - 'paper.kube.lmwpva.de'
          secretName: paperless-tls
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 96Mi
