# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore-secret
    namespace: monitoring-system
stringData:
    objstore.yml: ENC[AES256_GCM,data:76CxKIAicYwzZim9z0k7GSDEtegaK3YwxSq865Fk0MRZEfz5LceZAoMd+R7j+6vzQ9O6Ohonp1KRo6WiPpGhTx869X7ERlWnIFXlut635j+g3x6itY6snSmfk16gsu0IX3gyEKuxdcF6bRjGmO9/9S/onOo+HrxiTlNKCHHDLL7pwlX518UzueOvXmL5bBImM04oqO9x0lCrGAWyWxf3uP0HjoCYs8ZtvRvXzhYN,iv:bHAKACqNa2MQALxzzM4faDlrHeCNhl0See9DfLLesBY=,tag:CUDqIgV5s/d+bokl6PRNSA==,type:str]
    thanos.yml: ENC[AES256_GCM,data:EGw6UZAHDklEFp/kcGDRZYeMJT8L/ZoYrEbVfKm/OrILhOw0Wcd3iCp5eOgR0wLwkLxBGhiA4QCw96pXMPDV7zWNikzDexGW7iXjoGdrXa2jeue4Xo+HbERrVuDxVOMTPuKEneboPSBFpdTPaO2D4jymtVzfzHm18ftG3nwxsBB000pTrvGVZkU8ga5JA6YpNTosX0WWV9Svjyvs73eR1HEdJqjBG89K3weXiGZY,iv:9gKE/VdvO0R5sqDdrIZETFYZ7N/KK7aQ1iPKXyP64VI=,tag:hv5M1q0+pAcLWvcHDZC3pA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1du4ayen4huhh45xd2u26mp72jay2mlw9n6vhk7vkuhfqyy8x5adqfwm8kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSCtJSm1IUlFodlJSSkFH
            TjBpb25WckJQSTdsUjhpdFI4UTVQcjIwMVNzCmZVQUNDWk5XTUJhb25Rb2RZMVdG
            VlRpME1yazV1RDc4c1E0amErQU5OVjQKLS0tIE1jY28vRjFIV3l5aGJydnZDVDJ0
            NEFHQ1pxT1NEa2tiTFA0Rzc0S0VxWEEKXMPj9ypXs/AYW+PfedumnCdm1zP2ffDk
            77j0AkNLUU8Q5ccP2SxuhQ/dFTdOoNbrTU42gSitswvf/aJYfCKyxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-12T21:28:14Z"
    mac: ENC[AES256_GCM,data:tUK2eXhf/CQf5CJM7Nafp8qhdWmayKQDVmkDIKoy07WI3dd26BIkZoyMFmYkR0+Cy+ktXe2PUAnlqJJ+n4AbZDolFqNsAgK+ZvguFyCA8+l16LQvK7FnpWFDxf5FB0M5g0XdxX1ZWu+hg5RKvszbrxmIMIjRRQRGeRb4gmVWeA0=,iv:KqjCAjy2WlDfsyoQHRS5zXaur7MOSH1LOv1o8ACaTn8=,tag:N28u5gH20sWMArRwyfFQ+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
