---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-provisioner
  namespace: nfs-subdir
spec:
  interval: 1h
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.16
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir
        namespace: flux-system
      interval: 1h
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner
      tag: v4.0.2
    nfs:
      server: 10.0.10.10
      path: /volume1/kubedata
      mountOptions:
        - nfsvers=4.2
        - hard
        - noac
        - nocto
        - noacl
        - rsize=8192
        - wsize=8192
        - async
        - retrans=3
        - timeo=600
    storageClass:
      defaultClass: true
      provisionerName: k8s-sigs.io/nfs-subdir-external-provisioner
      pathPattern: '${.PVC.namespace}/${.PVC.annotations.nfs.io/storage-path}'
