apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - cert-manager
  - flux-system
  - nfs-subdir-external-provisioner
  - network-system
  - monitoring-system
  # - kube-system
  # - metallb-system
  # - system-upgrade
  # - system-monitoring
