---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-cluster-deployment
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/clusters/hekate/flux/deploy
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: cluster-k3s
