---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-cluster-issuer
spec:
  acme:
    email: '${SECRET_ACME_EMAIL}'
    server: https://step-certificates.networking.svc/acme/acme/directory
    privateKeySecretRef:
      name: acme-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: traefik
