---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app zigbee2mqtt
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: mosquitto
      namespace: home-automation
  values:
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.27.2
    # image:
    #   repository: ghcr.io/koenkk/zigbee2mqtt
    #   tag: ghcr.io/koenkk/zigbee2mqtt:1.27.2@sha256:89e3e23ddd4d1a9ee3897b33ca6b35c94b0f2b874f659cda79cd61e9dcb51d21

    env:
      TZ: '${TZ}'
      ZIGBEE2MQTT_DATA: /data

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        ingressClassName: 'traefik'
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: 'web'
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'router-wireless-settings'
        hosts:
          - host: &host '{{ .Release.Name }}.${INTERNAL_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        # tls:
        #   - hosts:
        #       - *host
    securityContext:
      # -- (bool) Privileged securityContext may be required if USB controller is accessed directly through the host machine
      privileged: true

    persistence:
      config:
        enabled: true
        existingClaim: zigbee2mqtt-config-v1
        mountPath: '/data'
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2654252-if00

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - zigbee-controller

    config:
      mqtt:
        server: mqtt://mosquitto
      # USB / Serial settings
      serial:
        # Location of your zigbee device
        port: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2654252-if00
        # Optional: adapter type, not needed unless you are experiencing problems (options: zstack, deconz)
        adapter: deconz

    resources:
      requests:
        cpu: 35m
        memory: 127M
      # limits:
      #   cpu: 35m
      #   memory: 127M
