# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore-secret
    namespace: system-monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:n8++nJJ0F4VbN2m02u/EELQ+RlEmC68wqzNVrrTvNwXcDNGGtfsrt9uvpSbrsbue47kYR/3tQN5riHLyoWpWbJYbnKqR6DXbGHsoVgiek7Zvz+cTJ+kYIq8IHbjDDzitS9RbHD+Ai8XzRFj6LorbsXkzSCDurUDlGFi8pzgHOO54HtzPpSpDhRr0fDtT,iv:woqu+tgrQIfLGxi+yEz4ITU2oYW2x/JuxpJsdoHWtlE=,tag:/XPmAWqXrJDs5ZYbgFZLuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1du4ayen4huhh45xd2u26mp72jay2mlw9n6vhk7vkuhfqyy8x5adqfwm8kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSCtJSm1IUlFodlJSSkFH
            TjBpb25WckJQSTdsUjhpdFI4UTVQcjIwMVNzCmZVQUNDWk5XTUJhb25Rb2RZMVdG
            VlRpME1yazV1RDc4c1E0amErQU5OVjQKLS0tIE1jY28vRjFIV3l5aGJydnZDVDJ0
            NEFHQ1pxT1NEa2tiTFA0Rzc0S0VxWEEKXMPj9ypXs/AYW+PfedumnCdm1zP2ffDk
            77j0AkNLUU8Q5ccP2SxuhQ/dFTdOoNbrTU42gSitswvf/aJYfCKyxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-08T01:25:30Z"
    mac: ENC[AES256_GCM,data:Uj2+zyPsysBw7vQNocWrIV5IfL7C+6zAs4kx+IHiwPgwgT+F6qb2IVvuIeDSosLQvHz/BYobQ0S/ZJyCZu2lU+6YJaAogvMxcpAlq9G+vJHGSrpgBUdWAbenDDN5qmMpFqDTlHl24Mvhk10E7QRJXU7M1XADGQ2Tl3D6KZZNkjM=,iv:dvPtVu9yeFifZOH97WA1Hi/TXS1DwXHviHM+MHxLrz0=,tag:MTmsMwET5Dvqk4uDNHBKGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
