# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore-secret
    namespace: system-monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:n8++nJJ0F4VbN2m02u/EELQ+RlEmC68wqzNVrrTvNwXcDNGGtfsrt9uvpSbrsbue47kYR/3tQN5riHLyoWpWbJYbnKqR6DXbGHsoVgiek7Zvz+cTJ+kYIq8IHbjDDzitS9RbHD+Ai8XzRFj6LorbsXkzSCDurUDlGFi8pzgHOO54HtzPpSpDhRr0fDtT,iv:woqu+tgrQIfLGxi+yEz4ITU2oYW2x/JuxpJsdoHWtlE=,tag:/XPmAWqXrJDs5ZYbgFZLuA==,type:str]
    objstoreConfig: ENC[AES256_GCM,data:7x/GBlrRpnqPOh02yGXoSghnIxy5L6XK/TwVXigJPcjva5j4+JcygruuDCe2DQuWxQTuOowa48FD3OXUzpo5+9Xw9rrBk1bvAe/kL6SXxPwNw8+dr689Gcge5osp1nO+42uaaaATMZAapvutuvO3P+A4hnVQb82aQmI/PPBJr2CxTeRiN/UJ2LQx5SyA,iv:PcMJuu7XSEb3dRDK0jjV3NDD9Bwo89uEc7zBYQxPMX0=,tag:9isjWvvHHp9kJTd6CuZ7yA==,type:str]
    objstore-config: ENC[AES256_GCM,data:hD6VA0FLtQvyeouvtPCi7oy2MhLXfDDfRKeaKqF4b1Fb5KBgBbhOrYWa16C1iuhTfwFHH5uY3TutJN9oeqe2MLZWmwuMpbvSYlCXbadVufv2qkU/NROOv6T5UiC/FtkvP3IWnyPW+6uF1a2emSaFixyaa7SurLMaXco2lzNuMtMQ1tbDLCcKQIhdUj0w,iv:2YXfAK94UG+kPRhnSFhpP/3vjR97bvd1KUYGWkH8nGs=,tag:lb7QapL6QcwO911DWCZWxQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1du4ayen4huhh45xd2u26mp72jay2mlw9n6vhk7vkuhfqyy8x5adqfwm8kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSCtJSm1IUlFodlJSSkFH
            TjBpb25WckJQSTdsUjhpdFI4UTVQcjIwMVNzCmZVQUNDWk5XTUJhb25Rb2RZMVdG
            VlRpME1yazV1RDc4c1E0amErQU5OVjQKLS0tIE1jY28vRjFIV3l5aGJydnZDVDJ0
            NEFHQ1pxT1NEa2tiTFA0Rzc0S0VxWEEKXMPj9ypXs/AYW+PfedumnCdm1zP2ffDk
            77j0AkNLUU8Q5ccP2SxuhQ/dFTdOoNbrTU42gSitswvf/aJYfCKyxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-08T01:49:20Z"
    mac: ENC[AES256_GCM,data:J4yo244OC3tZK/DHiQYZmnwsf0ekdevM+WmOhgW6zaq/wJnHOCDWZzSpJEWKmnvnQXgFgp5y8zsLoldCWigEmstKqUKQhcfobr6PVUvjcS16qHKNLPBXalJXLLYBb0aIJdpJWxW6Qb5+vqneDMbozV/AGgGNze8r6pZLJipMnvA=,iv:QY2NJdyuJcqo4oOpzbJwTN1HkzZbeiVg6kujVRJhbPc=,tag:8YQ0x18R+z+E5Xr31cCDPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
