---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    # - name: postgres
    #   namespace: databases
    - name: mosquitto
      namespace: home-automation
  values:
    image:
      repository: ghcr.io/onedr0p/home-assistant
      tag: 2022.9.2@sha256:f352e0d02860ed5aa73cbbf0a4b63728c9bf42a5367f9639dbaddf62f143289f

    env:
      TZ: '${TZ}'

    # envFrom:
    #   - secretRef:
    #       name: *app

    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: 'traefik'
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: 'web'
        #   external-dns.home.arpa/enabled: 'true'
        hosts:
          - host: &host 'hass.${INTERNAL_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        # tls:
        #   - hosts:
        #       - *host

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: 'OnRootMismatch'

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
      usb:
        enabled: true
        type: hostPath
        hostPath: '/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2654252-if00'
        mountPath: '/dev/ttyACM0'

    securityContext:
      # -- (bool) Privileged securityContext may be required if USB controller is accessed directly through the host machine
      privileged: true

    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.7.0
        env:
          TZ: '${TZ}'
        workingDir: '/config'
        args:
          - --auth
          - 'none'
          - --user-data-dir
          - '/config/.vscode'
          - --extensions-dir
          - '/config/.vscode'
        ingress:
          enabled: true
          ingressClassName: 'traefik'
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: 'web'
          hosts:
            - host: &host 'hass-code.${INTERNAL_DOMAIN}'
              paths:
                - path: /
                  pathType: Prefix
          # tls:
          #   - hosts:
          #       - *host
        volumeMounts:
          - name: config
            mountPath: /config

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      # limits:
      # memory: 96Mi
