---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    # - name: postgres
    #   namespace: databases
    - name: mosquitto
      namespace: home-automation
  values:
    image:
      # repository: ghcr.io/onedr0p/home-assistant
      tag: 2022.9.5

    env:
      TZ: '${TZ}'

    # envFrom:
    #   - secretRef:
    #       name: *app

    service:
      main:
        ports:
          http:
            port: 8123

    ingress:
      main:
        enabled: true
        ingressClassName: 'traefik'
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: 'web'
        #   external-dns.home.arpa/enabled: 'true'
        hosts:
          - host: &host 'hass.${INTERNAL_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        # tls:
        #   - hosts:
        #       - *host

    securityContext:
      privileged: true

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v2
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2654252-if00
        # hostPath: /dev/ttyACM0
        # mountPath: /dev/ttyACM0
        # hostPathType: CharDevice

    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.7.0
        env:
          TZ: '${TZ}'
        workingDir: '/config'
        args:
          - --auth
          - 'none'
          - --user-data-dir
          - '/config/.vscode'
          - --extensions-dir
          - '/config/.vscode'
        ingress:
          enabled: true
          ingressClassName: 'traefik'
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: 'web'
          hosts:
            - host: &host 'hass-code.${INTERNAL_DOMAIN}'
              paths:
                - path: /
                  pathType: Prefix
          # tls:
          #   - hosts:
          #       - *host
        volumeMounts:
          - name: config
            mountPath: /config

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - zigbee-controller

    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false

    # resources:
    #   requests:
    #     cpu: 50m
    #     memory: 64Mi
    # limits:
    # memory: 96Mi
