---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-pemstore
  namespace: cert-manager
  resourceVersion: '9978'
  selfLink: /api/v1/namespaces/cert-manager/configmaps/ca-pemstore
data:
  internal-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIBszCCAVmgAwIBAgIQZpnPVDGo5WKMGX6XaHFInDAKBggqhkjOPQQDAjA4MRYw
    FAYDVQQKEw1TbWFsbHN0ZXAgazNzMR4wHAYDVQQDExVTbWFsbHN0ZXAgazNzIFJv
    b3QgQ0EwHhcNMjIwNTI2MTEzNTQ2WhcNMzIwNTIzMTEzNTQ2WjA4MRYwFAYDVQQK
    Ew1TbWFsbHN0ZXAgazNzMR4wHAYDVQQDExVTbWFsbHN0ZXAgazNzIFJvb3QgQ0Ew
    WTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARGIAROWJ/GdfbHUcIdaQv8DBXZyMET
    VB3L0akxq8aEB9HNYGNDgvFy4LHsTzdXPTceXWPHo+zA4xC7lxxYcd3io0UwQzAO
    BgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUr90c
    /R8FAvHLHmpPwbEjADkrN90wCgYIKoZIzj0EAwIDSAAwRQIhAKhtsI2wKZvF7ZFO
    Ux6HrcHm2uPeXQF4swKb92RsdJpiAiAxJLzIvO8TBo/iaXUmqvuP0LRKNEiHFhNx
    gKjOBrqfrQ==
    -----END CERTIFICATE-----
