---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-pvc
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 128Mi
