---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: step-certificates-pvc
  namespace: networking
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
