---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: step-certificates
  namespace: networking
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    hajimari.io/enable: 'true'
    hajimari.io/icon: weather-sunset
    meta.helm.sh/release-name: step-certificates
    meta.helm.sh/release-namespace: default
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
status:
  loadBalancer:
    ingress:
      - ip: 10.0.3.200
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ca.${SECRET_DOMAIN}
      secretName: step-certificates-tls
  rules:
    - host: ca.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: step-certificates
                port:
                  number: 9000
