---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: emqx
      version: 5.0.3
      sourceRef:
        kind: HelmRepository
        name: emqx-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: public.ecr.aws/emqx/emqx

    replicaCount: 3
    recreatePods: true

    emqxConfig:
      EMQX_ALLOW_ANONYMOUS: 'false'
      EMQX_AUTH__MNESIA__PASSWORD_HASH: plain

    emqxAclConfig: >
      {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
      {allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
      {allow, all, subscribe, ["$SYS/#", {eq, "#"}]}.
      {allow, all}.
    emqxLoadedPlugins: >
      {emqx_management, true}.
      {emqx_recon, true}.
      {emqx_retainer, true}.
      {emqx_dashboard, true}.
      {emqx_telemetry, false}.
      {emqx_rule_engine, true}.
      {emqx_bridge_mqtt, false}.
      {emqx_auth_mnesia, true}.
      {emqx_prometheus, true}.
    emqxLoadedModules: >
      {emqx_mod_presence, true}.
      {emqx_mod_delayed, false}.
      {emqx_mod_rewrite, false}.
      {emqx_mod_subscription, false}.
      {emqx_mod_topic_metrics, true}.

    service:
      type: LoadBalancer
      loadBalancerIP: '${LB_EMQX}'
      externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        ingressClassName: 'traefik'
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: 'web'
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'resistor-nodes'
        hosts:
          - host: &host '{{ .Release.Name }}.${INTERNAL_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix

    metrics:
      enable: false

    persistence:
      enabled: true
      storageClass: nfs-client
      size: 100Mi

    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #         - matchExpressions:
    #             - key: app
    #               operator: In
    #               values:
    #                 - zigbee-controller

    resources:
      requests:
        cpu: 10m
        memory: 150M
      limits:
        # cpu: 15m
        memory: 512M

  valuesFrom:
    - targetPath: emqxConfig.EMQX_DASHBOARD__DEFAULT_PASSWORD
      kind: Secret
      name: emqx-config
      valuesKey: admin_password
    - targetPath: emqxConfig.EMQX_AUTH__USER__1__USERNAME
      kind: Secret
      name: emqx-config
      valuesKey: user_1_username
    - targetPath: emqxConfig.EMQX_AUTH__USER__1__PASSWORD
      kind: Secret
      name: emqx-config
      valuesKey: user_1_password
