kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: emqx-config
    namespace: home-automation
stringData:
    admin_password: ENC[AES256_GCM,data:Cp6eAKIazWdeBc8=,iv:3xcUtqCqCJigeycUm/6miVkSM+2UpkyV6P5iKeCLAOY=,tag:VU7bgzitjcjpZW35iXiI9w==,type:str]
    user_1_username: ENC[AES256_GCM,data:UhgHcg==,iv:VdXifvgwYY1Yn4yphe8JWjxiZCejGuR6Wt/+ycT6V9o=,tag:OPhb5FUx+QFk99oiTsvQ4g==,type:str]
    user_1_password: ENC[AES256_GCM,data:GK0f28erI4I=,iv:zJjACtDHjz/An8ThyaWx41an47C4TVYe2ngDFDLffMM=,tag:zsHSMSMPf1SuEowP3KxslQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1du4ayen4huhh45xd2u26mp72jay2mlw9n6vhk7vkuhfqyy8x5adqfwm8kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VWpEZzJMbDBDQ1lWS0d1
            RGEzMWIxRmxxNmdxNmZUempiSyt6VGdHVTNVCm5YZHJmVVNTWmxBVXJibFErSkFC
            TGh0RVlTN2xDdmx2RFN1dUJoU210WkEKLS0tIHZlM2xGM0JGZlhHOVJqWUtNRWhC
            V2JBTGVvL0VybDVxT2QyMnhQN3Nub2sKF4wpIqRHYtLKuD21W5D2vkJ1AKkPlg5J
            Kq/B/bWVLMCIHdJuC2mvGHDEvN+uS3L/O4Hgf0p+Up5H242zOx7P7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-23T21:49:13Z"
    mac: ENC[AES256_GCM,data:bAwQm7k7/jOUapLaImzjOyM9Iqa302dJBW8vj3OdOE/GeXXKy6hIt7Uro3oF5pG4RPg157B21SHJleEoHvTksT23uYTQvUN0qYVma9ELcrObNUl6dLObsA61JSA6/A8Zkn4hngNeazHyDhLoDopzsKKuZ+dEBzaopriWbscV0Z0=,iv:odCL9zhnGAqBzouD3PFQRakGcG7knwyeoZ2zINoq7B8=,tag:zurr5uoY78THiwC/l38KoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
