# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Jyl/VQ==,iv:fT09H3kw2l4LoIYDcofv4COaRDW17wtTZ7xVZKTCZrA=,tag:I3kSBjZWHL/KL5DCmclOHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1du4ayen4huhh45xd2u26mp72jay2mlw9n6vhk7vkuhfqyy8x5adqfwm8kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaThtZXBTdjFiRE1HOUYw
            cXcxUVlERzlLRFA4UkdBUW5TMUh0dzFRZ1RJCkVWNGRHNkJlS29yR0w4bFBsRTZa
            dFU0VHRRaXUyTUpPYlJiZ00xcjRUeDAKLS0tIGVRb0hReEZUK1BSeEEzSUpqVkRE
            TGJPWTg1RkFEZzRJNkxOUkt2Y2JVTHcKbsTNeR5bYARwUC78X11wbD+gGTFz9JIM
            3BO+iQD4WO63tsPbBxz8cKp0GjxaVs09Q3Nsp8A/0Wz8QwuV0JV8dA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-11T23:24:41Z"
    mac: ENC[AES256_GCM,data:MFxwjklTF4Z6wp+ZI7K6pOiHiNaOuzmr0Udxx8JlLMX0xDs/2G8pa3Tl3yP2Id/Q3sSZp2aYIo+FNiU8CwwQDRxicdcYyFAbLYVioR+1iPfxECyIY0y8J50wnlGoFIgEmcamMjOjBdJNV8xkUsEouu6rnG//tDhagIx0Co8T0ho=,iv:q+ieezpLmFB5azx0j/kcSGQdTze/vVZXwn1jzlvckjQ=,tag:fZxbPPvhgkHWSPqrRrxU3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
