# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: zigbee2mqtt-config
#   namespace: home-automation
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: nfs-client
#   resources:
#     requests:
#       storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
