---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: network-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb-charts
      version: 0.13.5
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
      interval: 10m
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # dependsOn:
  #   - name: kube-prometheus-stack
  #     namespace: system-monitoring
  values:
    prometheus:
      namespace: system-monitoring
      serviceAccount: prometheus-prometheus
      podMonitor:
        enabled: true
      prometheusRule:
        enabled: true

    speaker:
      tolerateMaster: true

    existingConfigMap: 'metallb-config'
    crds:
      enabled: true

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        cpu: 15m
        memory: 64M
