# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1du4ayen4huhh45xd2u26mp72jay2mlw9n6vhk7vkuhfqyy8x5adqfwm8kn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YWF3ZENOWC9rb2Yxa29G
            djRycDIrMHRvTVkwaGpQRDJrclJrR2lQWWw4CjdldDBWTGdrSExyd3BEV0U2Tk1m
            UlJwSGxZVFRmN3ROWi9ncnlBTGZLYUUKLS0tIDFuQlhtZ2JPYjY3dEMrTlBxa2lS
            VVlWb2RsVU5QV254ZUlkNnNsMVhSWlUK7kG7Ni928ek5BALWKu8GYRXAkTswiTZm
            u0iEaFpqPMp/bV/H4MmPlSqraCQk/x7d9d/swFs3AJkgi9P4B1QQOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-24T03:53:30Z"
    mac: ENC[AES256_GCM,data:/GbpvrQTcGLTkdtESzBFv47y72oJ0x7n2TGsokykEOo+M7BERrRVcA2hdGd/6U1EL2Ipfxq63DnonNN1fRdjrryIXctqFNY6H9jsauV+vRA3JuvhLrO5Rixvk7zOR0V9QbOPWj+BJeRlja7Ft2LsIGBHFTyvk3DxxzyEKn90Ez4=,iv:mjrliwZI4hAydOfyDdr90mogKbXbcjigj810N7gURRo=,tag:48uCc5dxZ/1ij3sKKtOAEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
