---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-network-system-metallb
  namespace: flux-system
spec:
  interval: 5m
  path: './k8s/manifests/core/network-system/metallb'
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: cluster-k3s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-network-system-metallb-custom-resources
  namespace: flux-system
spec:
  dependsOn:
    - name: core-network-system-metallb
  interval: 5m
  path: './k8s/manifests/core/network-system/metallb/custom-resources/'
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: cluster-k3s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-network-system-ingress-nginx
  namespace: flux-system
spec:
  interval: 5m
  path: './k8s/manifests/core/network-system/ingress-nginx'
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: cluster-k3s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-network-system-ingress-traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: core-network-system-metallb
  interval: 5m
  path: './k8s/manifests/core/network-system/traefik'
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: cluster-k3s
